Optime\SimpleSsoServerBundle\Entity\OneTimePassword:
  type: entity
  table: simple_sso_otp
  repositoryClass: Optime\SimpleSsoServerBundle\Entity\OneTimePasswordRepository
  id:
    otp:
      type: string
      generator:
        strategy: NONE
  fields:
    username:
      type: string
    application:
      type: string
    authData:
      column: auth_data
      type: text
    used:
      type: boolean