services:
  simple_sso_server.factory.otp:
    class: Optime\SimpleSsoServerBundle\Factory\OtpFactory
  simple_sso_server.generator.otp:
    class: Optime\SimpleSso\OneTimePassword\Service\OneTimePasswordGenerator
    arguments:
      - "@simple_sso_server.repository.otp"
      - "@simple_sso_server.factory.otp"
  simple_sso_server.security.public_password_checker:
    class: Optime\SimpleSso\Security\PublicPasswordChecker
    arguments:
      - "@simple_sso_server.default_application_repository"
  simple_sso_server.default_application_repository:
    class: Optime\SimpleSso\Application\InMemoryApplicationRepository
    arguments: ["%simple_sso_server.applications%"]
  simple_sso_server.security.listener.logout:
    class: Optime\SimpleSsoServerBundle\Security\EventListener\LogoutListener
    arguments:
      - "@simple_sso_server.cleaner.otp"
  simple_sso_server.repository.otp:
    class: Optime\SimpleSsoServerBundle\Entity\OneTimePasswordRepository
    factory: ["@doctrine.orm.entity_manager", "getRepository"]
    arguments: ["SimpleSsoServerBundle:OneTimePassword"]
  simple_sso_server.use_case.create_login_otp:
    class: Optime\SimpleSso\UseCase\CreateLoginOtpUseCase
    arguments:
      - "@simple_sso_server.generator.otp"
      - "@simple_sso_server.auth_data_resolver"
    public: true
  simple_sso_server.cleaner.otp:
    class: Optime\SimpleSso\OneTimePassword\Service\OneTimePasswordCleaner
    arguments:
      - "@simple_sso_server.repository.otp"
  simple_sso_server.use_case.get_credentials:
    class: Optime\SimpleSso\UseCase\GetCredentialsUseCase
    arguments:
      - "@simple_sso_server.repository.otp"
      - "@simple_sso_server.security.public_password_checker"
    public: true
  simple_sso_server.use_case.verify_active_session:
    class: Optime\SimpleSso\UseCase\VerifyActiveSessionUseCase
    arguments:
      - "@simple_sso_server.repository.otp"
      - "@simple_sso_server.security.public_password_checker"
    public: true
  simple_sso_server.security.listener.switch_user:
    class: Optime\SimpleSsoServerBundle\Security\EventListener\SwitchUserListener
    arguments:
      - "@security.token_storage"
      - "@simple_sso_server.cleaner.otp"
    tags:
      - { name: kernel.event_listener, event: security.switch_user, method: onSwitchUser }
  simple_sso_server.security.basic_auth_data_resolver:
    class: Optime\SimpleSsoServerBundle\Security\BasicAuthDataResolver
    arguments: ['@security.token_storage']
