<?php

namespace Optime\SimpleSsoServerBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Optime\Component\SingleSignOn\SimpleSso\OneTimePassword\OneTimePassword as OTPModel;
use Optime\Component\SingleSignOn\SimpleSso\OneTimePassword\OneTimePasswordRepositoryInterface;

/**
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OneTimePasswordRepository extends EntityRepository implements OneTimePasswordRepositoryInterface
{
    public function findByOtp($otp)
    {
        return $this->findOneBy(['otp' => $otp]);
    }

    public function findNotUsedByOtp($otp)
    {
        return $this->findOneBy([
            'otp' => $otp,
            'used' => false,
        ]);
    }

    public function findUsedByOtp($otp)
    {
        return $this->findOneBy([
            'otp' => $otp,
            'used' => true,
        ]);
    }

    public function save(OTPModel $oneTimePassword, $flush = true)
    {
        $this->_em->persist($oneTimePassword);
        $flush and $this->_em->flush($oneTimePassword);
    }

    public function removeByUsername($username, $flush = true)
    {
        $this->createQueryBuilder('otp')
            ->delete('SimpleSsoServerBundle:OneTimePassword', 'otp')
            ->where('otp.username = :username')
            ->setParameter('username', $username)
            ->getQuery()
            ->execute();
    }
}
